be:
  common:
    host: 192.168.33.12
    username: root
    password: password

server:
  port: 8001

management:
  server:
    port: -1 #关闭监控
  endpoints:
    enabled-by-default: false #关闭监控

spring:

  application:
    name: be-auth-web-20240703

  profiles:
    active: dev #按环境进行修改：prod

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  redis:
    host: ${be.common.host}
    password: ${be.common.password}
    port: 6001
